// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReLoop_Technologies_Web_App.Data;

#nullable disable

namespace ReLoop_Technologies_Web_App.Migrations
{
    [DbContext(typeof(ReLoopDbContext))]
    partial class ReLoopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReLoop_Technologies_Web_App.Data.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "CreatedAt");

                    b.ToTable("ActivityLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83588e8a-dc95-47bc-8d4c-e2dbff2f94c4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 10, 10, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Detail = "Recyclable PET 1 classified at 0.2 kg",
                            Title = "Plastic bottle scan saved",
                            Tone = "success",
                            UserAccountId = new Guid("2fc1f806-b68c-4a06-94fd-a97afcc24f2f")
                        },
                        new
                        {
                            Id = new Guid("30d55435-8355-44bb-a55e-7a9405490667"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 9, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Detail = "Recyclables collection booked for 12 May 2025",
                            Title = "Doorstep pickup scheduled",
                            Tone = "info",
                            UserAccountId = new Guid("2fc1f806-b68c-4a06-94fd-a97afcc24f2f")
                        },
                        new
                        {
                            Id = new Guid("86da6ff2-e9f4-4f0f-86cc-4caea9c8c080"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 8, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Detail = "+10 eco points added to Alex Rivera",
                            Title = "Reward points issued",
                            Tone = "success",
                            UserAccountId = new Guid("2fc1f806-b68c-4a06-94fd-a97afcc24f2f")
                        });
                });

            modelBuilder.Entity("ReLoop_Technologies_Web_App.Data.Entities.Pickup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("EstimatedWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("UserAccountId", "Status", "ScheduledFor");

                    b.ToTable("Pickups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5a53cb8-a41a-4b22-b541-d775f4f0b2d2"),
                            Address = "452 Eco Circular Ave, Suite 3B",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 9, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Paper and plastics",
                            ReferenceNumber = "#LP-9082",
                            ScheduledFor = new DateTimeOffset(new DateTime(2025, 5, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Scheduled",
                            UserAccountId = new Guid("2fc1f806-b68c-4a06-94fd-a97afcc24f2f"),
                            WasteType = "Recyclables"
                        },
                        new
                        {
                            Id = new Guid("8a151b65-8163-45ec-9fca-ae28f790d17c"),
                            Address = "452 Eco Circular Ave, Suite 3B",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 7, 8, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedWeightKg = 4.5m,
                            Notes = "Compost bag",
                            ReferenceNumber = "#LP-8931",
                            ScheduledFor = new DateTimeOffset(new DateTime(2025, 5, 8, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Completed",
                            UserAccountId = new Guid("2fc1f806-b68c-4a06-94fd-a97afcc24f2f"),
                            WasteType = "Organic"
                        },
                        new
                        {
                            Id = new Guid("d4a24c22-065b-47f6-a362-e7b168155ee0"),
                            Address = "452 Eco Circular Ave, Suite 3B",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 4, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedWeightKg = 1.2m,
                            Notes = "Plastic bottles",
                            ReferenceNumber = "#LP-8742",
                            ScheduledFor = new DateTimeOffset(new DateTime(2025, 5, 5, 11, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Completed",
                            UserAccountId = new Guid("2fc1f806-b68c-4a06-94fd-a97afcc24f2f"),
                            WasteType = "Recyclables"
                        },
                        new
                        {
                            Id = new Guid("b3ec780d-50f3-4779-b786-f54b8b49af9a"),
                            Address = "710 Greenwood Terrace",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 26, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Cancelled by user",
                            ReferenceNumber = "#LP-8521",
                            ScheduledFor = new DateTimeOffset(new DateTime(2025, 4, 28, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Cancelled",
                            UserAccountId = new Guid("2fc1f806-b68c-4a06-94fd-a97afcc24f2f"),
                            WasteType = "E-waste"
                        });
                });

            modelBuilder.Entity("ReLoop_Technologies_Web_App.Data.Entities.RewardLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "CreatedAt");

                    b.ToTable("RewardLedger");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1da8585b-e266-4d25-98b3-9e0206c5545b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 10, 10, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Points = 10,
                            Reason = "Plastic Bottle scan verified",
                            UserAccountId = new Guid("2fc1f806-b68c-4a06-94fd-a97afcc24f2f")
                        });
                });

            modelBuilder.Entity("ReLoop_Technologies_Web_App.Data.Entities.ScanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("EstimatedWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "ScannedAt");

                    b.ToTable("ScanRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11a63bf5-e562-41fa-968a-b87c32095939"),
                            Category = "Plastics (PET 1)",
                            Confidence = 94,
                            Disposition = "Recyclable",
                            EstimatedWeightKg = 0.2m,
                            FileName = "plastic-bottle.jpg",
                            ItemName = "Plastic Bottle",
                            PointsAwarded = 10,
                            ScannedAt = new DateTimeOffset(new DateTime(2025, 5, 10, 10, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserAccountId = new Guid("2fc1f806-b68c-4a06-94fd-a97afcc24f2f")
                        });
                });

            modelBuilder.Entity("ReLoop_Technologies_Web_App.Data.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fc1f806-b68c-4a06-94fd-a97afcc24f2f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "alex@example.com",
                            FullName = "Alex Rivera",
                            PasswordHash = "demo-password-only",
                            RewardPoints = 1200,
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("2a090ea4-dcf2-4327-a8b7-e2457092658e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@reloop.co.za",
                            FullName = "Mpho Admin",
                            PasswordHash = "demo-password-only",
                            RewardPoints = 0,
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ReLoop_Technologies_Web_App.Data.Entities.ActivityLog", b =>
                {
                    b.HasOne("ReLoop_Technologies_Web_App.Data.Entities.UserAccount", "UserAccount")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ReLoop_Technologies_Web_App.Data.Entities.Pickup", b =>
                {
                    b.HasOne("ReLoop_Technologies_Web_App.Data.Entities.UserAccount", "UserAccount")
                        .WithMany("Pickups")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ReLoop_Technologies_Web_App.Data.Entities.RewardLedgerEntry", b =>
                {
                    b.HasOne("ReLoop_Technologies_Web_App.Data.Entities.UserAccount", "UserAccount")
                        .WithMany("RewardLedger")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ReLoop_Technologies_Web_App.Data.Entities.ScanRecord", b =>
                {
                    b.HasOne("ReLoop_Technologies_Web_App.Data.Entities.UserAccount", "UserAccount")
                        .WithMany("ScanRecords")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ReLoop_Technologies_Web_App.Data.Entities.UserAccount", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Pickups");

                    b.Navigation("RewardLedger");

                    b.Navigation("ScanRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
